import type { EvidenceBundle } from '../types.js'
import { listOrNone, renderChangedFiles, testSummary } from './format.js'

export function renderPrBody(bundle: EvidenceBundle): string {
  const riskHints = bundle.autoCapture?.riskHints ?? []

  return `## Summary

${bundle.session.intent || bundle.session.title}

## Changes

${renderChangedFiles(bundle.gitSnapshot)}

## Tests

${testSummary(bundle.session)}

## Risks / Review Focus

${listOrNone(riskHints.map((hint) => hint.text), 'No risk hints generated.')}

## Notes

Generated by ForgeDesk from local git changes. This is review preparation, not a correctness claim.
`
}
