import type { EvidenceBundle } from '../types.js'
import { listOrNone, notVerified, renderChangedFiles, testSummary } from './format.js'

export function renderPrBody(bundle: EvidenceBundle): string {
  const riskHints = bundle.autoCapture?.riskHints ?? []
  const gaps = notVerified(bundle.session)

  return `## Summary

${bundle.session.intent || bundle.session.title}

## Changes

${renderChangedFiles(bundle.gitSnapshot)}

## Tests

${testSummary(bundle.session)}

## Reviewer Checklist

- [ ] Confirm the diff matches the stated intent.
- [ ] Review the changed files and risk focus before relying on tests.
- [ ] Check any known limits before merge or release.

## Risks / Review Focus

${listOrNone(riskHints.map((hint) => hint.text), 'No risk hints generated.')}

## Known Limits

${listOrNone(gaps, 'No known gaps recorded.')}

## Notes

Generated by ForgeDesk from local git changes. This is review preparation, not a correctness claim.
`
}
