import { chmod, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { runGit } from '../git/snapshot.js'
import { displayPath, listLinesOrNone } from '../templates/format.js'
import type { AutoMode } from '../types.js'
import { describeAutoMode, readAutoConfig } from './auto-config.js'
import { ForgeDeskError, isForgeDeskError } from './errors.js'
import { getNextReport, renderNextReport, type NextReport } from './next.js'
import { loadWorkspace, type Workspace } from './workspace.js'

export const HOOK_NAMES = ['pre-commit', 'pre-push'] as const
export type HookName = typeof HOOK_NAMES[number]

type HookState = 'installed' | 'missing' | 'unmanaged'
type HookOperation = 'installed' | 'removed' | 'skipped' | 'refused'
type HookRunOutcome = 'passed' | 'blocked'

export type HookStatus = {
  name: HookName
  state: HookState
  path: string
}

export type HooksStatusReport = {
  schemaVersion: 'forgedesk-hooks-status-v1'
  generatedAt: string
  repoPath: string
  autoMode: AutoMode
  hooks: HookStatus[]
  warnings: string[]
}

export type HooksInstallReport = {
  schemaVersion: 'forgedesk-hooks-install-v1'
  generatedAt: string
  repoPath: string
  autoMode: AutoMode
  hooks: Array<HookStatus & { operation: HookOperation }>
  warnings: string[]
}

export type HookRunReport = {
  schemaVersion: 'forgedesk-hook-run-v1'
  generatedAt: string
  repoPath: string
  hook: HookName
  autoMode: AutoMode
  outcome: HookRunOutcome
  summary: string
  recommendation: string
  nextReport?: NextReport
  warnings: string[]
  blockers: string[]
}

const managedMarker = 'forgedesk-hook: managed'
const hookVersion = 'forgedesk-hook-version: 1'

function isHookName(value: string): value is HookName {
  return HOOK_NAMES.includes(value as HookName)
}

export function parseHookName(value: string): HookName {
  if (!isHookName(value)) {
    throw new ForgeDeskError(`Hook must be one of: ${HOOK_NAMES.join(', ')}.`)
  }
  return value
}

function shellQuote(value: string): string {
  return `'${displayPath(value).replaceAll("'", "'\\''")}'`
}

function now(): string {
  return new Date().toISOString()
}

function hookDir(workspace: Workspace): string {
  const raw = runGit(workspace.repoPath, ['rev-parse', '--git-dir'])
  return path.isAbsolute(raw) ? raw : path.resolve(workspace.repoPath, raw)
}

function hookPath(workspace: Workspace, name: HookName): string {
  return path.join(hookDir(workspace), 'hooks', name)
}

async function readHook(filePath: string): Promise<string | undefined> {
  return readFile(filePath, 'utf8').catch((error) => {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') {
      return undefined
    }
    throw error
  })
}

function isManagedHook(content: string | undefined): boolean {
  return content !== undefined && content.includes(managedMarker)
}

async function hookStatus(workspace: Workspace, name: HookName): Promise<HookStatus> {
  const filePath = hookPath(workspace, name)
  const content = await readHook(filePath)
  return {
    name,
    path: filePath,
    state: content === undefined ? 'missing' : isManagedHook(content) ? 'installed' : 'unmanaged'
  }
}

async function autoMode(workspace: Workspace): Promise<AutoMode> {
  return (await readAutoConfig(workspace)).config.mode
}

function makeHookScript(repoPath: string, cliPath: string, hook: HookName): string {
  return [
    '#!/bin/sh',
    `# ${managedMarker}`,
    `# ${hookVersion}`,
    '# Generated by ForgeDesk. Remove with: forgedesk hooks uninstall',
    `cd ${shellQuote(repoPath)} || exit 1`,
    `exec ${shellQuote(process.execPath)} ${shellQuote(cliPath)} hooks run ${hook}`,
    ''
  ].join('\n')
}

async function statusReport(workspace: Workspace): Promise<HooksStatusReport> {
  const mode = await autoMode(workspace)
  const hooks = await Promise.all(HOOK_NAMES.map((name) => hookStatus(workspace, name)))
  const warnings = hooks
    .filter((hook) => hook.state === 'unmanaged')
    .map((hook) => `${hook.name} exists but is not managed by ForgeDesk.`)
  return {
    schemaVersion: 'forgedesk-hooks-status-v1',
    generatedAt: now(),
    repoPath: workspace.repoPath,
    autoMode: mode,
    hooks,
    warnings
  }
}

export async function getHooksStatus(cwd: string): Promise<HooksStatusReport> {
  return statusReport(await loadWorkspace(cwd))
}

export async function installHooks(cwd: string, cliPath: string): Promise<HooksInstallReport> {
  const workspace = await loadWorkspace(cwd)
  const mode = await autoMode(workspace)
  const hooks: HooksInstallReport['hooks'] = []
  const currentHooks = await Promise.all(HOOK_NAMES.map((name) => hookStatus(workspace, name)))
  const unmanaged = currentHooks.filter((hook) => hook.state === 'unmanaged')

  if (unmanaged.length > 0) {
    throw new ForgeDeskError(
      `Refusing to overwrite unmanaged git hook(s): ${unmanaged.map((hook) => hook.name).join(', ')}. Move or merge them manually, then run "forgedesk hooks install" again.`
    )
  }

  for (const current of currentHooks) {
    const name = current.name
    await writeFile(current.path, makeHookScript(workspace.repoPath, cliPath, name), 'utf8')
    await chmod(current.path, 0o755).catch(() => undefined)
    hooks.push({ ...(await hookStatus(workspace, name)), operation: 'installed' })
  }

  return {
    schemaVersion: 'forgedesk-hooks-install-v1',
    generatedAt: now(),
    repoPath: workspace.repoPath,
    autoMode: mode,
    hooks,
    warnings: mode === 'manual'
      ? ['Auto mode is manual. Installed hooks will stay idle until you change the auto profile.']
      : []
  }
}

export async function uninstallHooks(cwd: string): Promise<HooksInstallReport> {
  const workspace = await loadWorkspace(cwd)
  const mode = await autoMode(workspace)
  const hooks: HooksInstallReport['hooks'] = []

  for (const name of HOOK_NAMES) {
    const current = await hookStatus(workspace, name)
    if (current.state === 'installed') {
      await rm(current.path, { force: true })
      hooks.push({ ...(await hookStatus(workspace, name)), operation: 'removed' })
      continue
    }
    hooks.push({ ...current, operation: current.state === 'unmanaged' ? 'refused' : 'skipped' })
  }

  const warnings = hooks
    .filter((hook) => hook.state === 'unmanaged')
    .map((hook) => `${hook.name} is not managed by ForgeDesk and was left untouched.`)

  return {
    schemaVersion: 'forgedesk-hooks-install-v1',
    generatedAt: now(),
    repoPath: workspace.repoPath,
    autoMode: mode,
    hooks,
    warnings
  }
}

function passReport(
  workspace: Workspace,
  hook: HookName,
  mode: AutoMode,
  summary: string,
  recommendation: string,
  warnings: string[] = [],
  nextReport?: NextReport
): HookRunReport {
  return {
    schemaVersion: 'forgedesk-hook-run-v1',
    generatedAt: now(),
    repoPath: workspace.repoPath,
    hook,
    autoMode: mode,
    outcome: 'passed',
    summary,
    recommendation,
    nextReport,
    warnings,
    blockers: []
  }
}

function blockReport(
  workspace: Workspace,
  hook: HookName,
  mode: AutoMode,
  summary: string,
  recommendation: string,
  blockers: string[],
  nextReport?: NextReport
): HookRunReport {
  return {
    schemaVersion: 'forgedesk-hook-run-v1',
    generatedAt: now(),
    repoPath: workspace.repoPath,
    hook,
    autoMode: mode,
    outcome: 'blocked',
    summary,
    recommendation,
    nextReport,
    warnings: [],
    blockers
  }
}

function ignorableNextError(error: unknown): boolean {
  return isForgeDeskError(error, 'PROJECT_NOT_FOUND') || isForgeDeskError(error, 'NO_ACTIVE_SESSION')
}

export async function runHook(cwd: string, hook: HookName): Promise<HookRunReport> {
  const workspace = await loadWorkspace(cwd)
  const mode = await autoMode(workspace)
  const details = describeAutoMode(mode)

  if (mode === 'manual') {
    return passReport(
      workspace,
      hook,
      mode,
      'ForgeDesk hook is installed but idle because auto mode is manual.',
      'Run "forgedesk auto-config set assist" to enable advisory hook checks.'
    )
  }

  let nextReport: NextReport
  try {
    nextReport = await getNextReport(cwd, { dryRun: true })
  } catch (error) {
    if (ignorableNextError(error)) {
      return passReport(
        workspace,
        hook,
        mode,
        'ForgeDesk found no active local evidence work for this hook.',
        'Continue normally, or run "forgedesk next --dry-run" when you have a change to capture.'
      )
    }
    const message = error instanceof Error ? error.message : String(error)
    if (mode === 'guarded') {
      return blockReport(
        workspace,
        hook,
        mode,
        'ForgeDesk could not evaluate the local evidence gate.',
        'Fix the ForgeDesk error, then retry the git action.',
        [message]
      )
    }
    return passReport(
      workspace,
      hook,
      mode,
      'ForgeDesk could not evaluate the local evidence gate.',
      'Run "forgedesk doctor" for details.',
      [message]
    )
  }

  if (mode === 'local-auto' && nextReport.action !== 'blocked') {
    const actual = await getNextReport(cwd)
    return passReport(
      workspace,
      hook,
      mode,
      `ForgeDesk ran one local-auto step for ${hook}: ${actual.action}.`,
      actual.recommendation,
      actual.warnings,
      actual
    )
  }

  if (mode === 'guarded' && nextReport.action !== 'export') {
    return blockReport(
      workspace,
      hook,
      mode,
      `ForgeDesk blocked ${hook} because evidence is not ready.`,
      'Run "forgedesk next" until the evidence is ready, or change the auto profile.',
      nextReport.blockers.length > 0
        ? nextReport.blockers
        : [`Next action is ${nextReport.action} (${nextReport.reason}).`],
      nextReport
    )
  }

  return passReport(
    workspace,
    hook,
    mode,
    mode === 'guarded'
      ? `ForgeDesk allowed ${hook}; evidence is ready for export.`
      : `ForgeDesk checked ${hook} in ${mode} mode.`,
    nextReport.recommendation || details.summary,
    nextReport.action === 'export' ? [] : [`Next action is ${nextReport.action} (${nextReport.reason}).`],
    nextReport
  )
}

export function renderHooksStatus(report: HooksStatusReport): string {
  return [
    'ForgeDesk Hooks',
    '',
    `Repo: ${displayPath(report.repoPath)}`,
    `Auto mode: ${report.autoMode}`,
    '',
    '## Hooks',
    ...report.hooks.map((hook) => `- ${hook.name}: ${hook.state} (${displayPath(hook.path)})`),
    '',
    '## Warnings',
    ...listLinesOrNone(report.warnings),
    '',
    'Use "forgedesk hooks install" to install local git hooks and "forgedesk hooks uninstall" to remove ForgeDesk-managed hooks.'
  ].join('\n')
}

export function renderHooksInstall(report: HooksInstallReport): string {
  return [
    'ForgeDesk Hooks',
    '',
    `Repo: ${displayPath(report.repoPath)}`,
    `Auto mode: ${report.autoMode}`,
    '',
    '## Hooks',
    ...report.hooks.map((hook) => `- ${hook.name}: ${hook.operation} (${hook.state}) ${displayPath(hook.path)}`),
    '',
    '## Warnings',
    ...listLinesOrNone(report.warnings),
    '',
    'Hooks are local, explicit, and removable. They do not call AI, edit product code, run tests, commit, push, open PRs, tag, release, publish, upload, or run as a hidden background service.'
  ].join('\n')
}

export function renderHookRun(report: HookRunReport): string {
  return [
    'ForgeDesk Hook',
    '',
    report.summary,
    '',
    `Hook: ${report.hook}`,
    `Outcome: ${report.outcome}`,
    `Auto mode: ${report.autoMode}`,
    `Recommended next: ${report.recommendation}`,
    '',
    '## Blockers',
    ...listLinesOrNone(report.blockers),
    '',
    '## Warnings',
    ...listLinesOrNone(report.warnings),
    report.nextReport ? '' : undefined,
    report.nextReport ? '## Next Preview' : undefined,
    report.nextReport ? renderNextReport(report.nextReport) : undefined
  ].filter((line): line is string => line !== undefined).join('\n')
}
