import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { displayPath, listLinesOrNone } from '../templates/format.js'
import { ForgeDeskError } from './errors.js'
import { loadWorkspace, pathExists } from './workspace.js'

type IgnitionAction = 'status' | 'installed' | 'uninstalled'
type IgnitionState = 'installed' | 'missing' | 'conflict'

type VsCodeTask = {
  label?: string
  type?: string
  command?: string
  args?: string[]
  problemMatcher?: unknown[]
  detail?: string
  isBackground?: boolean
  runOptions?: {
    runOn?: string
    [key: string]: unknown
  }
  presentation?: Record<string, unknown>
  [key: string]: unknown
}

type VsCodeTasksFile = {
  version?: string
  tasks?: VsCodeTask[]
  [key: string]: unknown
}

export type IgnitionReport = {
  schemaVersion: 'forgedesk-ignition-v1'
  generatedAt: string
  action: IgnitionAction
  repoPath: string
  path: string
  state: IgnitionState
  taskLabel: string
  warnings: string[]
  next: string[]
}

const taskLabel = 'ForgeDesk: Ignition Watch'
const marker = 'Generated by ForgeDesk ignition'

function now(): string {
  return new Date().toISOString()
}

function tasksPath(repoPath: string): string {
  return path.join(repoPath, '.vscode', 'tasks.json')
}

async function readTasks(filePath: string): Promise<VsCodeTasksFile | undefined> {
  if (!(await pathExists(filePath))) {
    return undefined
  }
  try {
    const raw = await readFile(filePath, 'utf8')
    return JSON.parse(raw.replace(/^\uFEFF/, '')) as VsCodeTasksFile
  } catch {
    throw new ForgeDeskError(`Could not read VS Code tasks at ${displayPath(filePath)} as JSON.`)
  }
}

function ignitionTask(): VsCodeTask {
  return {
    label: taskLabel,
    type: 'shell',
    command: 'forgedesk',
    args: ['watch', '--quiet'],
    isBackground: true,
    problemMatcher: [],
    detail: marker,
    runOptions: {
      runOn: 'folderOpen'
    },
    presentation: {
      reveal: 'silent',
      panel: 'dedicated',
      clear: false
    }
  }
}

function stateFor(tasksFile: VsCodeTasksFile | undefined): IgnitionState {
  const tasks = Array.isArray(tasksFile?.tasks) ? tasksFile.tasks : []
  const task = tasks.find((item) => item.label === taskLabel)
  if (!task) {
    return 'missing'
  }
  return task.detail === marker ? 'installed' : 'conflict'
}

function mergeTask(tasksFile: VsCodeTasksFile | undefined): VsCodeTasksFile {
  const tasks = Array.isArray(tasksFile?.tasks) ? tasksFile.tasks : []
  const conflict = tasks.find((task) => task.label === taskLabel && task.detail !== marker)
  if (conflict) {
    throw new ForgeDeskError(
      `Refusing to overwrite unmanaged VS Code task: ${taskLabel}. Rename or remove it, then run "forgedesk ignition install" again.`
    )
  }
  return {
    version: tasksFile?.version ?? '2.0.0',
    ...tasksFile,
    tasks: [
      ...tasks.filter((task) => task.label !== taskLabel),
      ignitionTask()
    ]
  }
}

function removeTask(tasksFile: VsCodeTasksFile | undefined): VsCodeTasksFile {
  const tasks = Array.isArray(tasksFile?.tasks) ? tasksFile.tasks : []
  return {
    version: tasksFile?.version ?? '2.0.0',
    ...tasksFile,
    tasks: tasks.filter((task) => !(task.label === taskLabel && task.detail === marker))
  }
}

async function writeTasks(filePath: string, tasksFile: VsCodeTasksFile): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, `${JSON.stringify(tasksFile, null, 2)}\n`, 'utf8')
}

function report(
  action: IgnitionAction,
  repoPath: string,
  state: IgnitionState,
  warnings: string[],
  next: string[]
): IgnitionReport {
  return {
    schemaVersion: 'forgedesk-ignition-v1',
    generatedAt: now(),
    action,
    repoPath,
    path: tasksPath(repoPath),
    state,
    taskLabel,
    warnings,
    next
  }
}

export async function getIgnitionStatus(cwd: string): Promise<IgnitionReport> {
  const workspace = await loadWorkspace(cwd)
  const filePath = tasksPath(workspace.repoPath)
  return report(
    'status',
    workspace.repoPath,
    stateFor(await readTasks(filePath)),
    [],
    ['Run "forgedesk ignition install" to start ForgeDesk watch when this folder opens.']
  )
}

export async function installIgnition(cwd: string): Promise<IgnitionReport> {
  const workspace = await loadWorkspace(cwd)
  const filePath = tasksPath(workspace.repoPath)
  await writeTasks(filePath, mergeTask(await readTasks(filePath)))
  return report(
    'installed',
    workspace.repoPath,
    stateFor(await readTasks(filePath)),
    ['VS Code or Cursor may ask you to allow automatic tasks for this folder.'],
    ['Reopen the folder, allow automatic tasks if prompted, then ForgeDesk watch will start in the foreground task runner.']
  )
}

export async function uninstallIgnition(cwd: string): Promise<IgnitionReport> {
  const workspace = await loadWorkspace(cwd)
  const filePath = tasksPath(workspace.repoPath)
  await writeTasks(filePath, removeTask(await readTasks(filePath)))
  return report(
    'uninstalled',
    workspace.repoPath,
    stateFor(await readTasks(filePath)),
    [],
    ['Run "forgedesk ignition install" to recreate the folder-open watch task.']
  )
}

export function renderIgnitionReport(report: IgnitionReport): string {
  return [
    'ForgeDesk Ignition',
    '',
    `Action: ${report.action}`,
    `State: ${report.state}`,
    `Repo: ${displayPath(report.repoPath)}`,
    `Path: ${displayPath(report.path)}`,
    `Task: ${report.taskLabel}`,
    '',
    '## Warnings',
    ...listLinesOrNone(report.warnings),
    '',
    '## Next',
    ...listLinesOrNone(report.next),
    '',
    'Ignition is an explicit local folder-open task. It does not install a daemon, call AI, edit product code, commit, push, open PRs, tag, release, publish, upload, or run as a hidden background service.'
  ].join('\n')
}
