import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { displayPath, listLinesOrNone } from '../templates/format.js'
import { ForgeDeskError } from './errors.js'
import { discoverTestScripts, type DiscoveredTestScript } from './test-discovery.js'
import { loadWorkspace, pathExists } from './workspace.js'

type ShortcutAction = 'status' | 'installed' | 'uninstalled'
type ShortcutState = 'installed' | 'partial' | 'missing' | 'conflict' | 'skipped'

type VsCodeTask = {
  label?: string
  type?: string
  command?: string
  args?: string[]
  problemMatcher?: unknown[]
  detail?: string
  [key: string]: unknown
}

type VsCodeTasksFile = {
  version?: string
  tasks?: VsCodeTask[]
  [key: string]: unknown
}

type PackageJson = {
  scripts?: Record<string, string>
  [key: string]: unknown
}

export type ShortcutsOptions = {
  packageScripts?: boolean
  testTasks?: boolean
}

export type ShortcutsReport = {
  schemaVersion: 'forgedesk-shortcuts-v1'
  generatedAt: string
  action: ShortcutAction
  repoPath: string
  vscode: {
    path: string
    state: ShortcutState
    labels: string[]
  }
  testTasks: {
    state: ShortcutState
    labels: string[]
  }
  packageScripts: {
    path: string
    state: ShortcutState
    names: string[]
  }
  warnings: string[]
  next: string[]
}

const marker = 'Generated by ForgeDesk'

const vscodeTasks: Required<Pick<VsCodeTask, 'label' | 'type' | 'command' | 'args' | 'problemMatcher' | 'detail'>>[] = [
  {
    label: 'ForgeDesk: Next',
    type: 'shell',
    command: 'forgedesk',
    args: ['next'],
    problemMatcher: [],
    detail: marker
  },
  {
    label: 'ForgeDesk: Next Preview',
    type: 'shell',
    command: 'forgedesk',
    args: ['next', '--dry-run'],
    problemMatcher: [],
    detail: marker
  },
  {
    label: 'ForgeDesk: Doctor',
    type: 'shell',
    command: 'forgedesk',
    args: ['doctor'],
    problemMatcher: [],
    detail: marker
  },
  {
    label: 'ForgeDesk: Watch',
    type: 'shell',
    command: 'forgedesk',
    args: ['watch', '--quiet'],
    problemMatcher: [],
    detail: marker
  },
  {
    label: 'ForgeDesk: Inspect Export',
    type: 'shell',
    command: 'forgedesk',
    args: ['inspect', '--export'],
    problemMatcher: [],
    detail: marker
  }
]

const packageScripts: Record<string, string> = {
  'forgedesk:next': 'forgedesk next',
  'forgedesk:preview': 'forgedesk next --dry-run',
  'forgedesk:doctor': 'forgedesk doctor',
  'forgedesk:watch': 'forgedesk watch',
  'forgedesk:inspect-export': 'forgedesk inspect --export'
}

function now(): string {
  return new Date().toISOString()
}

function vscodeTasksPath(repoPath: string): string {
  return path.join(repoPath, '.vscode', 'tasks.json')
}

function packageJsonPath(repoPath: string): string {
  return path.join(repoPath, 'package.json')
}

function taskLabels(): string[] {
  return vscodeTasks.map((task) => task.label)
}

function testTaskLabel(script: DiscoveredTestScript): string {
  return `ForgeDesk Test: ${script.name}`
}

function testTasksFor(scripts: DiscoveredTestScript[]): VsCodeTask[] {
  return scripts.map((script) => ({
    label: testTaskLabel(script),
    type: 'shell',
    command: 'forgedesk',
    args: ['test', '--', script.runner, 'run', script.name],
    problemMatcher: [],
    detail: marker
  }))
}

function scriptNames(): string[] {
  return Object.keys(packageScripts)
}

async function readJsonFile<T>(filePath: string, label: string): Promise<T | undefined> {
  if (!(await pathExists(filePath))) {
    return undefined
  }
  try {
    const raw = await readFile(filePath, 'utf8')
    return JSON.parse(raw.replace(/^\uFEFF/, '')) as T
  } catch {
    throw new ForgeDeskError(`Could not read ${label} at ${displayPath(filePath)} as JSON.`)
  }
}

function taskState(tasksFile: VsCodeTasksFile | undefined): ShortcutState {
  if (!tasksFile) {
    return 'missing'
  }
  const tasks = Array.isArray(tasksFile.tasks) ? tasksFile.tasks : []
  const labels = new Set(taskLabels())
  const managed = tasks.filter((task) => task.label && labels.has(task.label) && task.detail === marker)
  const conflicts = tasks.filter((task) => task.label && labels.has(task.label) && task.detail !== marker)
  if (conflicts.length > 0) {
    return 'conflict'
  }
  if (managed.length === 0) {
    return 'missing'
  }
  return managed.length === labels.size ? 'installed' : 'partial'
}

function testTaskState(tasksFile: VsCodeTasksFile | undefined, labels: string[], includeTestTasks: boolean): ShortcutState {
  if (!includeTestTasks) {
    return 'skipped'
  }
  if (labels.length === 0) {
    return 'missing'
  }
  const tasks = Array.isArray(tasksFile?.tasks) ? tasksFile.tasks : []
  const labelSet = new Set(labels)
  const managed = tasks.filter((task) => task.label && labelSet.has(task.label) && task.detail === marker)
  const conflicts = tasks.filter((task) => task.label && labelSet.has(task.label) && task.detail !== marker)
  if (conflicts.length > 0) {
    return 'conflict'
  }
  if (managed.length === 0) {
    return 'missing'
  }
  return managed.length === labels.length ? 'installed' : 'partial'
}

function scriptsState(pkg: PackageJson | undefined, includePackageScripts: boolean): ShortcutState {
  if (!includePackageScripts) {
    return 'skipped'
  }
  if (!pkg) {
    return 'missing'
  }
  const scripts = pkg.scripts ?? {}
  const entries = Object.entries(packageScripts)
  const matching = entries.filter(([name, value]) => scripts[name] === value)
  const conflicts = entries.filter(([name, value]) => scripts[name] !== undefined && scripts[name] !== value)
  if (conflicts.length > 0) {
    return 'conflict'
  }
  if (matching.length === 0) {
    return 'missing'
  }
  return matching.length === entries.length ? 'installed' : 'partial'
}

async function readState(repoPath: string, includePackageScripts: boolean, testTaskLabels: string[] = [], includeTestTasks = false): Promise<{
  tasks: VsCodeTasksFile | undefined
  pkg: PackageJson | undefined
  vscodeState: ShortcutState
  testTaskState: ShortcutState
  packageState: ShortcutState
}> {
  const tasks = await readJsonFile<VsCodeTasksFile>(vscodeTasksPath(repoPath), 'VS Code tasks')
  const pkg = await readJsonFile<PackageJson>(packageJsonPath(repoPath), 'package.json')
  return {
    tasks,
    pkg,
    vscodeState: taskState(tasks),
    testTaskState: testTaskState(tasks, testTaskLabels, includeTestTasks),
    packageState: scriptsState(pkg, includePackageScripts)
  }
}

function report(
  action: ShortcutAction,
  repoPath: string,
  vscodeState: ShortcutState,
  testTaskStateValue: ShortcutState,
  testTaskLabels: string[],
  packageState: ShortcutState,
  warnings: string[],
  next: string[]
): ShortcutsReport {
  return {
    schemaVersion: 'forgedesk-shortcuts-v1',
    generatedAt: now(),
    action,
    repoPath,
    vscode: {
      path: vscodeTasksPath(repoPath),
      state: vscodeState,
      labels: taskLabels()
    },
    testTasks: {
      state: testTaskStateValue,
      labels: testTaskLabels
    },
    packageScripts: {
      path: packageJsonPath(repoPath),
      state: packageState,
      names: scriptNames()
    },
    warnings,
    next
  }
}

function mergeTasks(tasksFile: VsCodeTasksFile | undefined, extraTasks: VsCodeTask[] = []): VsCodeTasksFile {
  const currentTasks = Array.isArray(tasksFile?.tasks) ? tasksFile.tasks : []
  const labels = new Set([...taskLabels(), ...extraTasks.map((task) => task.label).filter((label): label is string => Boolean(label))])
  const conflicts = currentTasks.filter((task) => task.label && labels.has(task.label) && task.detail !== marker)
  if (conflicts.length > 0) {
    throw new ForgeDeskError(
      `Refusing to overwrite unmanaged VS Code task(s): ${conflicts.map((task) => task.label).join(', ')}. Rename or remove them, then run "forgedesk shortcuts install" again.`
    )
  }
  return {
    version: tasksFile?.version ?? '2.0.0',
    ...tasksFile,
    tasks: [
      ...currentTasks.filter((task) => !task.label || !labels.has(task.label)),
      ...vscodeTasks,
      ...extraTasks
    ]
  }
}

function removeTasks(tasksFile: VsCodeTasksFile | undefined, extraLabels: string[] = []): VsCodeTasksFile {
  const currentTasks = Array.isArray(tasksFile?.tasks) ? tasksFile.tasks : []
  const labels = new Set([...taskLabels(), ...extraLabels])
  return {
    version: tasksFile?.version ?? '2.0.0',
    ...tasksFile,
    tasks: currentTasks.filter((task) => !(task.label && labels.has(task.label) && task.detail === marker))
  }
}

function mergeScripts(pkg: PackageJson | undefined): PackageJson {
  const currentScripts = pkg?.scripts ?? {}
  const conflicts = Object.entries(packageScripts)
    .filter(([name, value]) => currentScripts[name] !== undefined && currentScripts[name] !== value)
    .map(([name]) => name)
  if (conflicts.length > 0) {
    throw new ForgeDeskError(
      `Refusing to overwrite unmanaged package script(s): ${conflicts.join(', ')}. Rename or remove them, then run "forgedesk shortcuts install --package-scripts" again.`
    )
  }
  return {
    ...pkg,
    scripts: {
      ...currentScripts,
      ...packageScripts
    }
  }
}

function removeScripts(pkg: PackageJson | undefined): PackageJson | undefined {
  if (!pkg) {
    return undefined
  }
  const scripts = { ...(pkg.scripts ?? {}) }
  for (const [name, value] of Object.entries(packageScripts)) {
    if (scripts[name] === value) {
      delete scripts[name]
    }
  }
  return {
    ...pkg,
    scripts
  }
}

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
}

export async function getShortcutsStatus(cwd: string, options: ShortcutsOptions = {}): Promise<ShortcutsReport> {
  const workspace = await loadWorkspace(cwd)
  const discovered = options.testTasks ? await discoverTestScripts(cwd) : undefined
  const testLabels = discovered?.scripts.map(testTaskLabel) ?? []
  const state = await readState(workspace.repoPath, options.packageScripts === true, testLabels, options.testTasks === true)
  return report(
    'status',
    workspace.repoPath,
    state.vscodeState,
    state.testTaskState,
    testLabels,
    state.packageState,
    [],
    ['Run "forgedesk shortcuts install" to generate editor tasks.']
  )
}

export async function installShortcuts(cwd: string, options: ShortcutsOptions = {}): Promise<ShortcutsReport> {
  const workspace = await loadWorkspace(cwd)
  const includePackageScripts = options.packageScripts === true
  const discovered = options.testTasks ? await discoverTestScripts(cwd) : undefined
  const testTasks = discovered ? testTasksFor(discovered.scripts) : []
  const testLabels = discovered?.scripts.map(testTaskLabel) ?? []
  const state = await readState(workspace.repoPath, includePackageScripts, testLabels, options.testTasks === true)
  const nextTasks = mergeTasks(state.tasks, testTasks)
  const nextPackage = includePackageScripts && state.pkg ? mergeScripts(state.pkg) : undefined

  const warnings: string[] = []
  if (includePackageScripts) {
    if (!state.pkg) {
      warnings.push('package.json was not found; package scripts were skipped.')
    }
  }
  if (options.testTasks && discovered && discovered.scripts.length === 0) {
    warnings.push('No test tasks were installed because no common package scripts were discovered.')
  }

  await writeJson(vscodeTasksPath(workspace.repoPath), nextTasks)
  if (nextPackage) {
    await writeJson(packageJsonPath(workspace.repoPath), nextPackage)
  }

  const nextState = await readState(workspace.repoPath, includePackageScripts, testLabels, options.testTasks === true)
  return report(
    'installed',
    workspace.repoPath,
    nextState.vscodeState,
    nextState.testTaskState,
    testLabels,
    nextState.packageState,
    warnings,
    ['Open VS Code Tasks and run "ForgeDesk: Next" or "ForgeDesk: Watch".']
  )
}

export async function uninstallShortcuts(cwd: string, options: ShortcutsOptions = {}): Promise<ShortcutsReport> {
  const workspace = await loadWorkspace(cwd)
  const includePackageScripts = options.packageScripts === true
  const discovered = options.testTasks ? await discoverTestScripts(cwd) : undefined
  const testLabels = discovered?.scripts.map(testTaskLabel) ?? []
  const state = await readState(workspace.repoPath, includePackageScripts, testLabels, options.testTasks === true)

  await writeJson(vscodeTasksPath(workspace.repoPath), removeTasks(state.tasks, testLabels))
  if (includePackageScripts && state.pkg) {
    await writeJson(packageJsonPath(workspace.repoPath), removeScripts(state.pkg))
  }

  const nextState = await readState(workspace.repoPath, includePackageScripts, testLabels, options.testTasks === true)
  return report(
    'uninstalled',
    workspace.repoPath,
    nextState.vscodeState,
    nextState.testTaskState,
    testLabels,
    nextState.packageState,
    [],
    ['Run "forgedesk shortcuts install" to recreate editor tasks.']
  )
}

export function renderShortcutsReport(report: ShortcutsReport): string {
  return [
    'ForgeDesk Shortcuts',
    '',
    `Action: ${report.action}`,
    `Repo: ${displayPath(report.repoPath)}`,
    `VS Code tasks: ${report.vscode.state} (${displayPath(report.vscode.path)})`,
    `Test tasks: ${report.testTasks.state}`,
    `Package scripts: ${report.packageScripts.state} (${displayPath(report.packageScripts.path)})`,
    '',
    '## VS Code Tasks',
    ...report.vscode.labels.map((label) => `- ${label}`),
    '',
    '## Package Scripts',
    ...report.packageScripts.names.map((name) => `- ${name}`),
    '',
    '## Test Tasks',
    ...listLinesOrNone(report.testTasks.labels),
    '',
    '## Warnings',
    ...listLinesOrNone(report.warnings),
    '',
    '## Next',
    ...listLinesOrNone(report.next),
    '',
    'Shortcuts are explicit local entry points. They do not call AI, edit product code, commit, push, open PRs, tag, release, publish, upload, or run as a hidden background service.'
  ].join('\n')
}
