import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { EvidenceBundle } from '../types.js'
import {
  changedFileCount,
  listOrNone,
  notVerified,
  renderChangedFiles,
  renderTestGroup,
  testSummary
} from '../templates/format.js'
import { pathExists, pathsFor } from './workspace.js'

export type TemplateInfo = {
  name: string
  builtin: boolean
  custom: boolean
}

export type TemplatesReport = {
  schemaVersion: 'forgedesk-templates-v1'
  generatedAt: string
  repoPath: string
  templatesDir: string
  templates: TemplateInfo[]
  customCount: number
  warnings: string[]
}

const CUSTOMIZABLE_TEMPLATES = ['PR_BODY.md', 'SUMMARY.md', 'REVIEW_CONTEXT.md', 'TEST_EVIDENCE.md'] as const

export const KNOWN_TEMPLATE_VARS = new Set([
  'session.title', 'session.status', 'session.intent',
  'git.branch', 'git.head', 'git.changedFiles',
  'project.name',
  'testSummary', 'testDetails',
  'riskHints', 'changedFiles',
  'decisions', 'manualChecks', 'notVerified'
])

export function templatesDirFor(repoPath: string): string {
  return path.join(pathsFor(repoPath).forgedeskDir, 'templates')
}

export async function loadCustomTemplate(repoPath: string, fileName: string): Promise<string | undefined> {
  const filePath = path.join(templatesDirFor(repoPath), fileName)
  if (!(await pathExists(filePath))) {
    return undefined
  }
  try {
    return await readFile(filePath, 'utf8')
  } catch {
    return undefined
  }
}

export function renderTemplate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+(?:\.\w+)?)\}\}/g, (match, key) => {
    return vars[key] ?? match
  })
}

export function validateTemplate(template: string, knownVars: Set<string> = KNOWN_TEMPLATE_VARS): string[] {
  const warnings: string[] = []
  const pattern = /\{\{(\w+(?:\.\w+)?)\}\}/g
  let match
  while ((match = pattern.exec(template)) !== null) {
    if (!knownVars.has(match[1])) {
      warnings.push(`Unknown template variable: {{${match[1]}}}`)
    }
  }
  return warnings
}

export async function resetTemplates(repoPath: string): Promise<string[]> {
  const dir = templatesDirFor(repoPath)
  const removed: string[] = []
  for (const name of CUSTOMIZABLE_TEMPLATES) {
    const filePath = path.join(dir, name)
    if (await pathExists(filePath)) {
      await rm(filePath)
      removed.push(name)
    }
  }
  return removed
}

export function buildTemplateVars(bundle: EvidenceBundle): Record<string, string> {
  const riskHints = bundle.autoCapture?.riskHints ?? []
  const gaps = notVerified(bundle.session)

  return {
    'session.title': bundle.session.title,
    'session.status': bundle.session.status,
    'session.intent': bundle.session.intent ?? 'Not recorded.',
    'git.branch': bundle.gitSnapshot.branch,
    'git.head': bundle.gitSnapshot.head,
    'git.changedFiles': String(changedFileCount(bundle.gitSnapshot)),
    'project.name': bundle.project.name,
    'testSummary': testSummary(bundle.session),
    'testDetails': renderTestGroup(bundle.session.tests),
    'riskHints': listOrNone(
      riskHints.map((h) => `${h.text} (${h.source}, ${h.confidence})`),
      'No risk hints generated.'
    ),
    'changedFiles': renderChangedFiles(bundle.gitSnapshot),
    'decisions': listOrNone(
      bundle.session.decisions.map((d) => d.text),
      'None'
    ),
    'manualChecks': listOrNone(
      (bundle.session.manualChecks ?? []).map((c) => c.text),
      'None'
    ),
    'notVerified': listOrNone(gaps, 'No known gaps recorded.')
  }
}

export function isCustomizableTemplate(fileName: string): boolean {
  return (CUSTOMIZABLE_TEMPLATES as readonly string[]).includes(fileName)
}

const EXAMPLE_TEMPLATES: Record<string, string> = {
  'PR_BODY.md': `## Summary

{{session.intent}}

## Changes

{{changedFiles}}

## Tests

{{testSummary}}

## Reviewer Checklist

- [ ] Confirm the diff matches the stated intent.
- [ ] Review the changed files and risk focus before relying on tests.
- [ ] Check any known limits before merge or release.

## Risks / Review Focus

{{riskHints}}

## Known Limits

{{notVerified}}

## Notes

Generated by ForgeDesk from local git changes. This is review preparation, not a correctness claim.
`,
  'SUMMARY.md': `# ForgeDesk Summary

## Status

{{session.status}}

## Change

{{session.intent}}

## Files

- Changed files: {{git.changedFiles}}
- Branch: {{git.branch}}
- HEAD: {{git.head}}

## Tests

{{testSummary}}

## Risk Hints

{{riskHints}}

## Decisions

{{decisions}}

## Manual Checks

{{manualChecks}}

This summary prepares review context. It is not a code review verdict.
`,
  'REVIEW_CONTEXT.md': `# Review Context

## At A Glance

- Session: {{session.title}}
- Status: {{session.status}}
- Branch: {{git.branch}}
- HEAD: {{git.head}}
- Changed files: {{git.changedFiles}}

## Change Intent

{{session.intent}}

## Changed Files

{{changedFiles}}

## Risk Hints

{{riskHints}}

## Test Evidence

{{testSummary}}

## Reviewer Checklist

- Confirm the implementation matches the stated intent.
- Inspect the changed files before relying on generated summaries.
- Treat failed, missing, or recorded-only tests as blockers until addressed.
- Review risk hints and known limits explicitly.

## Known Limits

{{notVerified}}

## Review Instructions

- Check whether the diff matches the stated intent.
- Focus on the risk hints above.
- Use tests as supporting evidence, not proof of correctness.
- Do not assume correctness based only on this context.

ForgeDesk prepares review context. It does not review or approve code.
`,
  'TEST_EVIDENCE.md': `# Test Evidence

## Summary

{{testSummary}}

## Details

{{testDetails}}

## Decisions

{{decisions}}

## Manual Checks

{{manualChecks}}

## Not Verified

{{notVerified}}

This is local test evidence, not a correctness verdict.
`
}

export async function initTemplates(repoPath: string): Promise<string[]> {
  const dir = templatesDirFor(repoPath)
  await mkdir(dir, { recursive: true })
  const written: string[] = []

  for (const [name, content] of Object.entries(EXAMPLE_TEMPLATES)) {
    const filePath = path.join(dir, name)
    if (!(await pathExists(filePath))) {
      await writeFile(filePath, content, 'utf8')
      written.push(name)
    }
  }

  return written
}

export async function getTemplatesReport(cwd: string): Promise<TemplatesReport> {
  const { loadWorkspace } = await import('./workspace.js')
  const workspace = await loadWorkspace(cwd)
  const dir = templatesDirFor(workspace.repoPath)
  const warnings: string[] = []

  const templates: TemplateInfo[] = []
  for (const name of CUSTOMIZABLE_TEMPLATES) {
    const customPath = path.join(dir, name)
    const custom = await pathExists(customPath)
    templates.push({ name, builtin: true, custom })
  }

  const customCount = templates.filter((t) => t.custom).length

  return {
    schemaVersion: 'forgedesk-templates-v1',
    generatedAt: new Date().toISOString(),
    repoPath: workspace.repoPath,
    templatesDir: displayPath(dir),
    templates,
    customCount,
    warnings
  }
}

function displayPath(filePath: string): string {
  return filePath.replaceAll('\\', '/')
}
